version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: raj
      MYSQL_DATABASE: doctor_booking_db
      MYSQL_USER: deepak
      MYSQL_PASSWORD: raj
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    ports:
      - "3306:3306"
    networks:
      - hms-network

  bookingservice:
    build:
      context: ../Booking
    container_name: booking_service
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/doctor_booking_db
      SPRING_DATASOURCE_USERNAME: deepak
      SPRING_DATASOURCE_PASSWORD: raj
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - hms-network

  gatewayserver:
    build:
      context: ../gatewayServer
    container_name: gateway_server
    ports:
      - "8081:8081"
    networks:
      - hms-network

  notificationservice:
    build:
      context: ../notification
    container_name: notification_service
    ports:
      - "8083:8083"
    networks:
      - hms-network
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
    - 2181:2181
    networks:
      - hms-network
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
    - zookeeper
    ports:
    - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
        - hms-network
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-8
    ports:
    - 8082:8080
    depends_on:
    - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

    networks:
      - hms-network

networks:
  hms-network:
    driver: bridge
